"""Add new changes

Revision ID: 00e30da66e80
Revises: 6cacdff7367b
Create Date: 2023-12-16 14:43:57.177793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e30da66e80'
down_revision: Union[str, None] = '6cacdff7367b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutzer', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutzer', 'created_at')
    # ### end Alembic commands ###
