"""Add new changes

Revision ID: 172a6aa9be2e
Revises: 
Create Date: 2023-12-16 16:40:12.703162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172a6aa9be2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adresse',
    sa.Column('adresse_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('strasse', sa.String(), nullable=True),
    sa.Column('hausnummer', sa.Integer(), nullable=True),
    sa.Column('zusatz', sa.String(), nullable=True),
    sa.Column('plz', sa.Integer(), nullable=True),
    sa.Column('stadt', sa.String(), nullable=True),
    sa.Column('land', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('adresse_id')
    )
    op.create_table('netzbetreiber',
    sa.Column('user_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('preisstrukturen',
    sa.Column('preis_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('bezugspreis_kwh', sa.Float(), nullable=True),
    sa.Column('einspeisung_kwh', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('preis_id')
    )
    op.create_table('tarif',
    sa.Column('tarif_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('tarifname', sa.String(), nullable=True),
    sa.Column('preis_kwh', sa.Float(), nullable=True),
    sa.Column('grundgebuehr', sa.Float(), nullable=True),
    sa.Column('laufzeit', sa.Integer(), nullable=True),
    sa.Column('spezielle_konditionen', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tarif_id'),
    sa.UniqueConstraint('tarifname')
    )
    op.create_table('nutzer',
    sa.Column('user_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nachname', sa.String(), nullable=True),
    sa.Column('vorname', sa.String(), nullable=True),
    sa.Column('geburtsdatum', sa.Date(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('passwort', sa.String(), nullable=True),
    sa.Column('rolle', sa.Enum('Haushalte', 'Solarteure', 'Energieberatende', 'Netzbetreiber', 'Admin', name='rolle'), nullable=False),
    sa.Column('telefonnummer', sa.String(), nullable=True),
    sa.Column('adresse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['adresse_id'], ['adresse.adresse_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('dashboard_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('haushalt_id', sa.Integer(), nullable=True),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.Column('pv_erzeugung', sa.Float(), nullable=True),
    sa.Column('soc', sa.Float(), nullable=True),
    sa.Column('batterie_leistung', sa.Float(), nullable=True),
    sa.Column('zaehler', sa.Float(), nullable=True),
    sa.Column('last', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['haushalt_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_data_id'), 'dashboard_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_data_id'), table_name='dashboard_data')
    op.drop_table('dashboard_data')
    op.drop_table('nutzer')
    op.drop_table('tarif')
    op.drop_table('preisstrukturen')
    op.drop_table('netzbetreiber')
    op.drop_table('adresse')
    # ### end Alembic commands ###
