"""Add new changes

Revision ID: 25bde5a8ec0a
Revises: 28811417f8bb
Create Date: 2023-12-24 01:07:18.185028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25bde5a8ec0a'
down_revision: Union[str, None] = '28811417f8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('haushalte_dashboard_id_fkey', 'haushalte', type_='foreignkey')
    op.drop_column('haushalte', 'dashboard_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('haushalte', sa.Column('dashboard_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('haushalte_dashboard_id_fkey', 'haushalte', 'dashboard_smartmeter_data', ['dashboard_id'], ['id'])
    # ### end Alembic commands ###
