"""Add new changes

Revision ID: 3dcbc52e105f
Revises: 3e83fe53ba9b
Create Date: 2023-12-17 22:45:43.725922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dcbc52e105f'
down_revision: Union[str, None] = '3e83fe53ba9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preisstrukturen', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('preisstrukturen', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'preisstrukturen', 'nutzer', ['user_id'], ['user_id'])
    op.add_column('tarif', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('tarif', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'tarif', 'nutzer', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tarif', type_='foreignkey')
    op.drop_column('tarif', 'created_at')
    op.drop_column('tarif', 'user_id')
    op.drop_constraint(None, 'preisstrukturen', type_='foreignkey')
    op.drop_column('preisstrukturen', 'created_at')
    op.drop_column('preisstrukturen', 'user_id')
    # ### end Alembic commands ###
