"""neu aufsetzen

Revision ID: 44770e8ac795
Revises: 442c60c7e450
Create Date: 2023-12-23 11:54:12.422153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44770e8ac795'
down_revision: Union[str, None] = '442c60c7e450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Vertrag', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('Vertrag_haushalt_id_fkey', 'Vertrag', type_='foreignkey')
    op.create_foreign_key(None, 'Vertrag', 'Nutzer', ['user_id'], ['user_id'])
    op.drop_column('Vertrag', 'haushalt_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Vertrag', sa.Column('haushalt_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Vertrag', type_='foreignkey')
    op.create_foreign_key('Vertrag_haushalt_id_fkey', 'Vertrag', 'Nutzer', ['haushalt_id'], ['user_id'])
    op.drop_column('Vertrag', 'user_id')
    # ### end Alembic commands ###
