"""Add new changes

Revision ID: 69ac345be39a
Revises: abfcb2d71384
Create Date: 2023-12-16 21:52:53.343795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ac345be39a'
down_revision: Union[str, None] = 'abfcb2d71384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pvanlage',
    sa.Column('anlage_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('haushalt_id', sa.Integer(), nullable=True),
    sa.Column('solarteur_id', sa.Integer(), nullable=True),
    sa.Column('netzbetreiber_id', sa.Integer(), nullable=True),
    sa.Column('modultyp', sa.String(), nullable=True),
    sa.Column('kapazitaet', sa.Float(), nullable=True),
    sa.Column('installationsflaeche', sa.Float(), nullable=True),
    sa.Column('installationsdatum', sa.Date(), nullable=True),
    sa.Column('modulanordnung', sa.Enum('Nord', 'Nordost', 'Ost', 'Suedost', 'Sued', 'Suedwest', 'West', 'Nordwest', name='orientierung'), nullable=False),
    sa.Column('kabelwegfuehrung', sa.String(), nullable=True),
    sa.Column('montagesystem', sa.Enum('Aufdachmontage', 'Indachmontage', 'Flachdachmontage', 'Freilandmontage', 'Trackermontage', 'Fassadenmontage', name='montagesystem'), nullable=False),
    sa.Column('schattenanalyse', sa.Enum('Kein_Schatten', 'Minimalschatten', 'Moderater_Schatten', 'Ausgedehnter_Schatten', 'Dauerhafter_Schatten', name='schatten'), nullable=False),
    sa.Column('wechselrichterposition', sa.String(), nullable=True),
    sa.Column('installationsplan', sa.String(), nullable=True),
    sa.Column('prozess_status', sa.Enum('AnfrageGestellt', 'AngebotGemacht', 'AngebotAngenommen', 'PlanErstellt', 'Abgenommen', 'InstallationAbgeschlossen', name='prozessstatus'), nullable=False),
    sa.Column('nvpruefung_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['haushalt_id'], ['nutzer.user_id'], ),
    sa.ForeignKeyConstraint(['netzbetreiber_id'], ['nutzer.user_id'], ),
    sa.ForeignKeyConstraint(['solarteur_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('anlage_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pvanlage')
    # ### end Alembic commands ###
