"""Add new changes

Revision ID: 866415f7a5b3
Revises: 8daa64495085
Create Date: 2023-12-18 13:55:47.540866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '866415f7a5b3'
down_revision: Union[str, None] = '8daa64495085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pvanlage', 'modulanordnung',
               existing_type=postgresql.ENUM('Nord', 'Nordost', 'Ost', 'Suedost', 'Sued', 'Suedwest', 'West', 'Nordwest', name='orientierung'),
               nullable=True)
    op.alter_column('pvanlage', 'montagesystem',
               existing_type=postgresql.ENUM('Aufdachmontage', 'Indachmontage', 'Flachdachmontage', 'Freilandmontage', 'Trackermontage', 'Fassadenmontage', name='montagesystem'),
               nullable=True)
    op.alter_column('pvanlage', 'schattenanalyse',
               existing_type=postgresql.ENUM('Kein_Schatten', 'Minimalschatten', 'Moderater_Schatten', 'Ausgedehnter_Schatten', 'Dauerhafter_Schatten', name='schatten'),
               nullable=True)
    op.alter_column('pvanlage', 'prozess_status',
               existing_type=postgresql.ENUM('AnfrageGestellt', 'AngebotGemacht', 'AngebotAngenommen', 'PlanErstellt', 'Genehmigt', 'Abgenommen', 'InstallationAbgeschlossen', name='prozessstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pvanlage', 'prozess_status',
               existing_type=postgresql.ENUM('AnfrageGestellt', 'AngebotGemacht', 'AngebotAngenommen', 'PlanErstellt', 'Genehmigt', 'Abgenommen', 'InstallationAbgeschlossen', name='prozessstatus'),
               nullable=False)
    op.alter_column('pvanlage', 'schattenanalyse',
               existing_type=postgresql.ENUM('Kein_Schatten', 'Minimalschatten', 'Moderater_Schatten', 'Ausgedehnter_Schatten', 'Dauerhafter_Schatten', name='schatten'),
               nullable=False)
    op.alter_column('pvanlage', 'montagesystem',
               existing_type=postgresql.ENUM('Aufdachmontage', 'Indachmontage', 'Flachdachmontage', 'Freilandmontage', 'Trackermontage', 'Fassadenmontage', name='montagesystem'),
               nullable=False)
    op.alter_column('pvanlage', 'modulanordnung',
               existing_type=postgresql.ENUM('Nord', 'Nordost', 'Ost', 'Suedost', 'Sued', 'Suedwest', 'West', 'Nordwest', name='orientierung'),
               nullable=False)
    # ### end Alembic commands ###
