"""Add new changes

Revision ID: 8daa64495085
Revises: 
Create Date: 2023-12-18 13:21:01.313180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8daa64495085'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adresse',
    sa.Column('adresse_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('strasse', sa.String(), nullable=True),
    sa.Column('hausnummer', sa.Integer(), nullable=True),
    sa.Column('zusatz', sa.String(), nullable=True),
    sa.Column('plz', sa.Integer(), nullable=True),
    sa.Column('stadt', sa.String(), nullable=True),
    sa.Column('land', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('adresse_id')
    )
    op.create_table('netzbetreiber',
    sa.Column('user_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('nutzer',
    sa.Column('user_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nachname', sa.String(), nullable=True),
    sa.Column('vorname', sa.String(), nullable=True),
    sa.Column('geburtsdatum', sa.Date(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('passwort', sa.String(), nullable=True),
    sa.Column('rolle', sa.Enum('Haushalte', 'Solarteure', 'Energieberatende', 'Netzbetreiber', 'Admin', name='rolle'), nullable=False),
    sa.Column('telefonnummer', sa.String(), nullable=True),
    sa.Column('adresse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['adresse_id'], ['adresse.adresse_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('dashboard_smartmeter_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('haushalt_id', sa.Integer(), nullable=True),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.Column('pv_erzeugung', sa.Float(), nullable=True),
    sa.Column('soc', sa.Float(), nullable=True),
    sa.Column('batterie_leistung', sa.Float(), nullable=True),
    sa.Column('zaehler', sa.Float(), nullable=True),
    sa.Column('last', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['haushalt_id'], ['nutzer.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_smartmeter_data_id'), 'dashboard_smartmeter_data', ['id'], unique=False)
    op.create_table('preisstrukturen',
    sa.Column('preis_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('bezugspreis_kwh', sa.Float(), nullable=True),
    sa.Column('einspeisung_kwh', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('preis_id')
    )
    op.create_table('pvanlage',
    sa.Column('anlage_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('haushalt_id', sa.Integer(), nullable=True),
    sa.Column('solarteur_id', sa.Integer(), nullable=True),
    sa.Column('netzbetreiber_id', sa.Integer(), nullable=True),
    sa.Column('modultyp', sa.String(), nullable=True),
    sa.Column('kapazitaet', sa.Float(), nullable=True),
    sa.Column('installationsflaeche', sa.Float(), nullable=True),
    sa.Column('installationsdatum', sa.Date(), nullable=True),
    sa.Column('modulanordnung', sa.Enum('Nord', 'Nordost', 'Ost', 'Suedost', 'Sued', 'Suedwest', 'West', 'Nordwest', name='orientierung'), nullable=False),
    sa.Column('kabelwegfuehrung', sa.String(), nullable=True),
    sa.Column('montagesystem', sa.Enum('Aufdachmontage', 'Indachmontage', 'Flachdachmontage', 'Freilandmontage', 'Trackermontage', 'Fassadenmontage', name='montagesystem'), nullable=False),
    sa.Column('schattenanalyse', sa.Enum('Kein_Schatten', 'Minimalschatten', 'Moderater_Schatten', 'Ausgedehnter_Schatten', 'Dauerhafter_Schatten', name='schatten'), nullable=False),
    sa.Column('wechselrichterposition', sa.String(), nullable=True),
    sa.Column('installationsplan', sa.String(), nullable=True),
    sa.Column('prozess_status', sa.Enum('AnfrageGestellt', 'AngebotGemacht', 'AngebotAngenommen', 'PlanErstellt', 'Genehmigt', 'Abgenommen', 'InstallationAbgeschlossen', name='prozessstatus'), nullable=False),
    sa.Column('nvpruefung_status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['haushalt_id'], ['nutzer.user_id'], ),
    sa.ForeignKeyConstraint(['netzbetreiber_id'], ['nutzer.user_id'], ),
    sa.ForeignKeyConstraint(['solarteur_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('anlage_id')
    )
    op.create_table('tarif',
    sa.Column('tarif_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('tarifname', sa.String(), nullable=True),
    sa.Column('preis_kwh', sa.Float(), nullable=True),
    sa.Column('grundgebuehr', sa.Float(), nullable=True),
    sa.Column('laufzeit', sa.Integer(), nullable=True),
    sa.Column('spezielle_konditionen', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('tarif_id'),
    sa.UniqueConstraint('tarifname')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarif')
    op.drop_table('pvanlage')
    op.drop_table('preisstrukturen')
    op.drop_index(op.f('ix_dashboard_smartmeter_data_id'), table_name='dashboard_smartmeter_data')
    op.drop_table('dashboard_smartmeter_data')
    op.drop_table('nutzer')
    op.drop_table('netzbetreiber')
    op.drop_table('adresse')
    # ### end Alembic commands ###
