"""Add new changes

Revision ID: 9601cdc1c0eb
Revises: a2d1f0139796
Create Date: 2023-12-18 16:32:00.022262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9601cdc1c0eb'
down_revision: Union[str, None] = 'a2d1f0139796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adresse', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('adresse', sa.Column('latitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adresse', 'latitude')
    op.drop_column('adresse', 'longitude')
    # ### end Alembic commands ###
