"""Add new changes

Revision ID: 9f8cfcbbb16e
Revises: 79697dfe9467
Create Date: 2023-12-22 21:23:25.113122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8cfcbbb16e'
down_revision: Union[str, None] = '79697dfe9467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energieausweise',
    sa.Column('energieausweis_id', sa.Integer(), nullable=False),
    sa.Column('haushalt_id', sa.Integer(), nullable=False),
    sa.Column('massnahmen_id', sa.Integer(), nullable=True),
    sa.Column('energieberater_id', sa.Integer(), nullable=True),
    sa.Column('energieeffizienzklasse', sa.String(), nullable=True),
    sa.Column('verbrauchskennwerte', sa.Float(), nullable=True),
    sa.Column('ausstellungsdatum', sa.Date(), nullable=True),
    sa.Column('gueltigkeit', sa.Date(), nullable=True),
    sa.Column('ausweis_status', sa.Enum('AnfrageGestellt', 'Ausgestellt', name='ausweisstatus'), nullable=False),
    sa.ForeignKeyConstraint(['energieberater_id'], ['nutzer.user_id'], ),
    sa.ForeignKeyConstraint(['haushalt_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('energieausweis_id')
    )
    op.create_table('kalendereintraege',
    sa.Column('kalender_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('zeitpunkt', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('beschreibung', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('kalender_id')
    )
    op.add_column('angebote', sa.Column('angebotsstatus', sa.Boolean(), nullable=True))
    op.add_column('angebote', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('angebote', 'installationsflaeche')
    op.drop_column('angebote', 'modultyp')
    op.drop_column('angebote', 'kapazitaet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('angebote', sa.Column('kapazitaet', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('angebote', sa.Column('modultyp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('angebote', sa.Column('installationsflaeche', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('angebote', 'created_at')
    op.drop_column('angebote', 'angebotsstatus')
    op.drop_table('kalendereintraege')
    op.drop_table('energieausweise')
    # ### end Alembic commands ###
