"""Add new changes

Revision ID: a2d1f0139796
Revises: 3dcbc52e105f
Create Date: 2023-12-17 23:22:31.886107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d1f0139796'
down_revision: Union[str, None] = '3dcbc52e105f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_smartmeter_data', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dashboard_smartmeter_data', 'nutzer', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dashboard_smartmeter_data', type_='foreignkey')
    op.drop_column('dashboard_smartmeter_data', 'user_id')
    # ### end Alembic commands ###
