"""Add new changes

Revision ID: ad43846c50a3
Revises: ee127ce9a856
Create Date: 2023-12-18 16:40:42.272280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad43846c50a3'
down_revision: Union[str, None] = 'ee127ce9a856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('angebote', sa.Column('anlage_id', sa.Integer(), nullable=True))
    op.add_column('angebote', sa.Column('kosten', sa.Float(), nullable=True))
    op.alter_column('angebote', 'kapazitaet',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint('angebote_user_id_fkey', 'angebote', type_='foreignkey')
    op.create_foreign_key(None, 'angebote', 'pvanlage', ['anlage_id'], ['anlage_id'])
    op.drop_column('angebote', 'user_id')
    op.drop_column('angebote', 'installationsdatum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('angebote', sa.Column('installationsdatum', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('angebote', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'angebote', type_='foreignkey')
    op.create_foreign_key('angebote_user_id_fkey', 'angebote', 'nutzer', ['user_id'], ['user_id'])
    op.alter_column('angebote', 'kapazitaet',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('angebote', 'kosten')
    op.drop_column('angebote', 'anlage_id')
    # ### end Alembic commands ###
