"""empty message

Revision ID: c6ae787d0efb
Revises: d168255ff03b
Create Date: 2023-12-26 23:54:29.567846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ae787d0efb'
down_revision: Union[str, None] = 'd168255ff03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_id_tarif_id_uc', 'Vertrag', ['user_id', 'tarif_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_id_tarif_id_uc', 'Vertrag', type_='unique')
    # ### end Alembic commands ###

"""Add new changes

Revision ID: b0d02f228eb7
Revises: e4105606365e
Create Date: 2023-12-23 15:28:47.070641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d02f228eb7'
down_revision: Union[str, None] = 'e4105606365e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarif', sa.Column('netzbetreiber_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tarif', 'nutzer', ['netzbetreiber_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tarif', type_='foreignkey')
    op.drop_column('tarif', 'netzbetreiber_id')
    # ### end Alembic commands ###
