"""Add new changes

Revision ID: e4105606365e
Revises: 9f8cfcbbb16e
Create Date: 2023-12-23 15:19:59.828197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4105606365e'
down_revision: Union[str, None] = '9f8cfcbbb16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energieberatende',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spezialisierung', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('haushalt',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anzahl_bewohner', sa.Integer(), nullable=True),
    sa.Column('heizungsart', sa.String(), nullable=True),
    sa.Column('baujahr', sa.Integer(), nullable=True),
    sa.Column('wohnflaeche', sa.Float(), nullable=True),
    sa.Column('isolierungsqualitaet', sa.Enum('hoch', 'mittel', 'niedrig', name='isolierungsqualitaet'), nullable=True),
    sa.Column('ausrichtung_dach', sa.Enum('Nord', 'Nordost', 'Ost', 'Suedost', 'Sued', 'Suedwest', 'West', 'Nordwest', name='ausrichtungdach'), nullable=True),
    sa.Column('dachflaeche', sa.Float(), nullable=True),
    sa.Column('energieeffizienzklasse', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('rechnungen',
    sa.Column('rechnung_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rechnungsbetrag', sa.Float(), nullable=True),
    sa.Column('rechnungsdatum', sa.Date(), nullable=True),
    sa.Column('faelligkeitsdatum', sa.Date(), nullable=True),
    sa.Column('rechnungsart', sa.Enum('Netzbetreiber_Rechnung', 'Energieberater_Rechnung', 'Solarteur_Rechnung', name='rechnungsart'), nullable=True),
    sa.Column('zeitraum', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('rechnung_id')
    )
    op.create_table('solarteur',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('vertrag',
    sa.Column('vertrag_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tarif_id', sa.Integer(), nullable=True),
    sa.Column('beginn_datum', sa.Date(), nullable=True),
    sa.Column('end_datum', sa.Date(), nullable=True),
    sa.Column('jahresabschlag', sa.Float(), nullable=True),
    sa.Column('vertragstatus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tarif_id'], ['tarif.tarif_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('vertrag_id')
    )
    op.drop_constraint('tarif_user_id_fkey', 'tarif', type_='foreignkey')
    op.drop_column('tarif', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarif', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tarif_user_id_fkey', 'tarif', 'nutzer', ['user_id'], ['user_id'])
    op.drop_table('vertrag')
    op.drop_table('solarteur')
    op.drop_table('rechnungen')
    op.drop_table('haushalt')
    op.drop_table('energieberatende')
    # ### end Alembic commands ###
