"""Add new changes

Revision ID: ee127ce9a856
Revises: 866415f7a5b3
Create Date: 2023-12-18 15:06:26.290041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee127ce9a856'
down_revision: Union[str, None] = '866415f7a5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('angebote',
    sa.Column('angebot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('modultyp', sa.String(), nullable=True),
    sa.Column('kapazitaet', sa.Integer(), nullable=True),
    sa.Column('installationsflaeche', sa.Integer(), nullable=True),
    sa.Column('installationsdatum', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('angebot_id')
    )
    op.create_index(op.f('ix_angebote_angebot_id'), 'angebote', ['angebot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_angebote_angebot_id'), table_name='angebote')
    op.drop_table('angebote')
    # ### end Alembic commands ###
