"""neu aufsetzen

Revision ID: fa77a7d26e60
Revises: 8c00af354a9d
Create Date: 2023-12-23 11:45:47.720486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa77a7d26e60'
down_revision: Union[str, None] = '8c00af354a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Vertrag_haushalt_id_fkey', 'Vertrag', type_='foreignkey')
    op.create_foreign_key(None, 'Vertrag', 'Nutzer', ['haushalt_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Vertrag', type_='foreignkey')
    op.create_foreign_key('Vertrag_haushalt_id_fkey', 'Vertrag', 'Haushalt', ['haushalt_id'], ['user_id'])
    # ### end Alembic commands ###
